Config:
  time: 30
  check:
    task: false # Czy ma sprawdzac taskiem
    event: true # Czy ma sprawdzac eventem
Limits:
  limit1:
    material: "1" # Format "nazwa lub id"
    material-type: false # jezeli false to wyczytuje z pola nizej id jak true to nazwe
    data: 0 # Data itemu
    player-amount: 16 # Limit dla gracza
    vip-amount: 32 # Limit dla gracza z powiekszonym limitem
    vip-permission: "vip.limits" # Permisja powiekszenia limitu
    messages:
      move-item:
      - "&6{AMOUNT} kamienia zostalo przeniesione do enderchesta!"
      drop-item:
      - "&6{AMOUNT} kamienia zostalo wyrzucone obok Ciebie!"
